# Use an official Node.js runtime as a parent image
FROM node:18-alpine as BUILD_IMAGE

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the application
RUN npm run build

# FROM node:18-alpine as PRODUCTION_IMAGE
# WORKDIR /app

# COPY --from=BUILD_IMAGE /app/dist/ /app/dist/
# # Expose the port the app runs on

# COPY package.json .
# COPY vite.config.js .
# COPY tailwind.config.js .
# COPY postcss.config.js . 

# RUN npm install -g vite

EXPOSE 5173

# Define the command to run the app
CMD ["npm", "run", "preview"] 